Citizen.CreateThread(function()
    while true do
	Wait(60000)
	   SetWeaponDamageModifier(GetHashKey("weapon_rpg"), 0)
    	Wait(0)
    	SetWeaponDamageModifier(GetHashKey("weapon_grenade"), 0) 
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_stickybomb"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_railgun"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_hominglauncher"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_compactlauncher"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_rayminigun"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_firework"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_grenadelauncher"),0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_pipebomb"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_proxmine"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("WEAPON_SMOKEGRENADE"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("WEAPON_BZGAS"), 0)
        Wait(0)
        SetWeaponDamageModifier(GetHashKey("weapon_minigun"), 0)
        Wait(0)
		SetWeaponDamageModifier(3204302209, 0)
        Wait(0)
		SetWeaponDamageModifier(375527679, 0)
        Wait(0)
		SetWeaponDamageModifier(324506233, 0)
        Wait(0)
		SetWeaponDamageModifier(GetHashKey("WEAPON_UNARMED"), 0.5)
        Wait(0)
		SetWeaponDamageModifier(GetHashKey("WEAPON_NIGHTSTICK"), 0.2)
        Wait(0)
		SetWeaponDamageModifier(GetHashKey("WEAPON_PUMPSHOTGUN"), 0.30)
        Wait(0)
		SetWeaponDamageModifier(GetHashKey("weapon_doubleaction"), 0.60)
        Wait(0)
    end
end)

--[[Citizen.CreateThread(function()
    while true do
        Citizen.Wait(0)
	local ped = PlayerPedId()
        if IsPedArmed(ped, 6) then
	       DisableControlAction(1, 140, true)
       	   DisableControlAction(1, 141, true)
           DisableControlAction(1, 142, true)
        end
    end
end)]]